// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Custom API Routes
 *
 * This file is the editable surface for custom backend logic that
 * doesn't fit the auto-generated CRUD model (per-model GET/POST/PATCH/
 * DELETE under `/api/<model>s`). Anything you mount on the exported
 * Hono app shows up at `/api/...` alongside the generated CRUD routes.
 *
 * Examples:
 *   - Aggregations / dashboards: `app.get('/dashboard', ...)`
 *   - Webhooks: `app.post('/webhooks/stripe', ...)`
 *   - Auth flows: `app.post('/auth/login', ...)`
 *
 * For installed integrations (Jira, Slack, Google, Meta Ads, etc.):
 *
 * - Dashboards / list views / "my X" pages → mount a route HERE that
 *   uses `getServerToolsClient()`. Resolve identity per request with
 *   `<TOOLKIT>_GET_CURRENT_USER`, compose the calls you need, return
 *   a clean shape your component owns.
 *
 *   The SDK auto-parses tool result `data` on success (the runtime
 *   JSON.stringifies tool responses; @shogo-ai/sdk/tools >=1.3 parses
 *   them back). Index `data` like a plain object — do NOT write a
 *   `JSON.parse(result.data)` helper. Pass a generic to `execute<T>()`
 *   for typed access.
 *
 *   import { getServerToolsClient } from '@shogo-ai/sdk/tools'
 *
 *   app.get('/jira/my-issues', async (c) => {
 *     const tools = getServerToolsClient()
 *     const me = await tools.execute<{ accountId: string }>('JIRA_GET_CURRENT_USER', {})
 *     if (!me.ok || !me.data?.accountId) {
 *       return c.json({ error: me.error ?? 'not authenticated' }, 401)
 *     }
 *     const issues = await tools.execute<{ issues: unknown[] }>('JIRA_SEARCH_ISSUES', {
 *       jql: `assignee = "${me.data.accountId}"`,
 *     })
 *     if (!issues.ok) return c.json({ error: issues.error ?? 'search failed' }, 502)
 *     return c.json({ issues: issues.data?.issues ?? [] })
 *   })
 *
 *   In the browser, surface the server's `error` field — never throw
 *   `new Error('Failed to load X')`:
 *
 *     const res = await fetch('/api/jira/my-issues')
 *     const body = await res.json().catch(() => ({}))
 *     if (!res.ok) setError(body.error ?? `HTTP ${res.status}`)
 *     else setIssues(body.issues ?? [])
 *
 *   After writing or editing a route, hit it to confirm shape + status:
 *     curl -s -w "\nHTTP %{http_code}\n" http://localhost:$RUNTIME_PORT/api/jira/my-issues
 *   A green build proves the file compiled, not that the endpoint works.
 *
 * - Ad-hoc interactive actions (button clicks, form submits) → use
 *   `useTools()` directly in the component. Don't add a route here for
 *   single-call passthroughs.
 *
 * Hand-rolling a `fetch()` to the provider's REST API will fail
 * because the pod has no provider tokens — auth lives in the runtime.
 * NEVER hardcode the agent operator's identity (accountId, member id,
 * userId) into route code; resolve it per request as shown above.
 *
 * The runtime watches this file. Saving triggers a fast restart of
 * `server.tsx` (no schema regeneration, no `prisma db push`) so changes
 * land in under a second.
 *
 * The Prisma client is available — import it from `./src/lib/db`:
 *
 *   import { prisma } from './src/lib/db'
 *
 *   app.get('/stats', async (c) => {
 *     const userCount = await prisma.user.count()
 *     return c.json({ userCount })
 *   })
 *
 * Do NOT edit `server.tsx` — it is auto-generated by the SDK from
 * `shogo.config.json` and will be overwritten on the next regeneration.
 */

import { Hono } from 'hono'
import { prisma } from './src/lib/db'

const app = new Hono()

// ── LLM Usage ──────────────────────────────────────────────
app.get('/llm-usage', async (c) => {
  const { model, provider, from, to, groupBy } = c.req.query()
  const where: Record<string, unknown> = {}
  if (model) where.model = model
  if (provider) where.provider = provider
  if (from || to) {
    where.createdAt = {
      ...(from ? { gte: new Date(from) } : {}),
      ...(to ? { lte: new Date(to) } : {}),
    }
  }

  if (groupBy === 'model') {
    const rows = await prisma.lLMUsage.groupBy({
      by: ['model'],
      _sum: { inputTokens: true, outputTokens: true, totalTokens: true, cost: true },
      _count: true,
      _avg: { latencyMs: true },
      where,
      orderBy: { _sum: { cost: 'desc' } },
    })
    return c.json({ groups: rows })
  }
  if (groupBy === 'provider') {
    const rows = await prisma.lLMUsage.groupBy({
      by: ['provider'],
      _sum: { inputTokens: true, outputTokens: true, totalTokens: true, cost: true },
      _count: true,
      _avg: { latencyMs: true },
      where,
      orderBy: { _sum: { cost: 'desc' } },
    })
    return c.json({ groups: rows })
  }
  if (groupBy === 'hour') {
    const all = await prisma.lLMUsage.findMany({ where, orderBy: { createdAt: 'asc' } })
    const buckets: Record<string, { tokens: number; cost: number; count: number; latency: number; inputTokens: number; outputTokens: number }> = {}
    for (const row of all) {
      const key = new Date(row.createdAt).toISOString().slice(0, 13)
      if (!buckets[key]) buckets[key] = { tokens: 0, cost: 0, count: 0, latency: 0, inputTokens: 0, outputTokens: 0 }
      buckets[key].tokens += row.totalTokens
      buckets[key].cost += row.cost
      buckets[key].count += 1
      buckets[key].latency += row.latencyMs
      buckets[key].inputTokens += row.inputTokens
      buckets[key].outputTokens += row.outputTokens
    }
    const result = Object.entries(buckets).map(([hour, data]) => ({
      hour,
      tokens: data.tokens,
      inputTokens: data.inputTokens,
      outputTokens: data.outputTokens,
      cost: Math.round(data.cost * 10000) / 10000,
      count: data.count,
      avgLatency: data.count > 0 ? Math.round(data.latency / data.count) : 0,
    }))
    return c.json({ timeline: result })
  }

  const items = await prisma.lLMUsage.findMany({
    where,
    orderBy: { createdAt: 'desc' },
    take: 200,
  })
  const summary = await prisma.lLMUsage.aggregate({
    where,
    _sum: { inputTokens: true, outputTokens: true, totalTokens: true, cost: true },
    _count: true,
    _avg: { latencyMs: true },
  })
  return c.json({
    items,
    summary: {
      totalTokens: summary._sum.totalTokens ?? 0,
      inputTokens: summary._sum.inputTokens ?? 0,
      outputTokens: summary._sum.outputTokens ?? 0,
      totalCost: Math.round((summary._sum.cost ?? 0) * 10000) / 10000,
      count: summary._count,
      avgLatency: Math.round(summary._avg.latencyMs ?? 0),
    },
  })
})

app.post('/llm-usage', async (c) => {
  const body = await c.req.json()
  const totalTokens = (body.inputTokens ?? 0) + (body.outputTokens ?? 0)
  const usage = await prisma.lLMUsage.create({
    data: {
      provider: body.provider,
      model: body.model,
      inputTokens: body.inputTokens ?? 0,
      outputTokens: body.outputTokens ?? 0,
      totalTokens,
      cost: body.cost ?? 0,
      latencyMs: body.latencyMs ?? 0,
      status: body.status ?? 'success',
      agentName: body.agentName,
      sessionId: body.sessionId,
      traceId: body.traceId,
      spanId: body.spanId,
      errorMessage: body.errorMessage,
      metadata: body.metadata ? JSON.stringify(body.metadata) : null,
    },
  })
  return c.json(usage, 201)
})

// ── Budget Rules ────────────────────────────────────────────
app.get('/budget-rules', async (c) => {
  const rules = await prisma.budgetRule.findMany({ orderBy: { createdAt: 'desc' } })
  return c.json({ items: rules })
})

app.post('/budget-rules', async (c) => {
  const body = await c.req.json()
  if (body.id) {
    const updated = await prisma.budgetRule.update({ where: { id: body.id }, data: body })
    return c.json(updated)
  }
  const created = await prisma.budgetRule.create({ data: body })
  return c.json(created, 201)
})

app.delete('/budget-rules/:id', async (c) => {
  const id = c.req.param('id')
  await prisma.budgetRule.delete({ where: { id } })
  return c.json({ ok: true })
})

// ── Budget Alerts ───────────────────────────────────────────
app.get('/budget-alerts', async (c) => {
  const items = await prisma.budgetAlert.findMany({ orderBy: { createdAt: 'desc' }, take: 100 })
  return c.json({ items })
})

app.post('/budget-alerts/:id/acknowledge', async (c) => {
  const id = c.req.param('id')
  await prisma.budgetAlert.update({ where: { id }, data: { acknowledged: true } })
  return c.json({ ok: true })
})

// ── Budget Check (evaluate rules against current usage) ─────
app.post('/budget-check', async (c) => {
  const rules = await prisma.budgetRule.findMany({ where: { enabled: true } })
  const firedAlerts: unknown[] = []
  const now = new Date()

  for (const rule of rules) {
    const since = rule.limitType === 'daily'
      ? new Date(now.getFullYear(), now.getMonth(), now.getDate())
      : rule.limitType === 'monthly'
        ? new Date(now.getFullYear(), now.getMonth(), 1)
        : new Date(0)

    const agg = await prisma.lLMUsage.aggregate({
      where: { createdAt: { gte: since } },
      _sum: { totalTokens: true, cost: true },
    })
    const currentTokens = agg._sum.totalTokens ?? 0
    const currentCost = agg._sum.cost ?? 0

    let fired = false
    let alertType = ''
    let threshold = rule.alertThreshold
    let limitTokens: number | null = null
    let limitCost: number | null = null

    if (rule.maxTokens && currentTokens >= rule.maxTokens * rule.alertThreshold) {
      fired = true
      alertType = 'token_threshold'
      limitTokens = rule.maxTokens
      threshold = currentTokens / rule.maxTokens
    }
    if (rule.maxCost && currentCost >= rule.maxCost * rule.alertThreshold) {
      fired = true
      alertType = alertType ? 'both_threshold' : 'cost_threshold'
      limitCost = rule.maxCost
      threshold = Math.max(threshold, currentCost / rule.maxCost)
    }

    if (fired) {
      const alert = await prisma.budgetAlert.create({
        data: {
          ruleId: rule.id,
          ruleName: rule.name,
          alertType,
          currentTokens,
          currentCost: Math.round(currentCost * 10000) / 10000,
          limitTokens,
          limitCost,
          threshold: Math.round(threshold * 100) / 100,
          message: `${rule.name}: ${alertType.includes('token') ? `${currentTokens} tokens used (${Math.round(threshold * 100)}%)` : `$${currentCost.toFixed(4)} spent (${Math.round(threshold * 100)}%)`}`,
        },
      })
      firedAlerts.push(alert)
    }
  }
  return c.json({ firedAlerts, checked: rules.length })
})

// ── SRE Incidents ───────────────────────────────────────────
app.get('/sre/incidents', async (c) => {
  const { status } = c.req.query()
  const where = status ? { status } : {}
  const items = await prisma.sREIncident.findMany({ where, orderBy: { createdAt: 'desc' } })
  return c.json({ items })
})

app.post('/sre/incidents', async (c) => {
  const body = await c.req.json()
  const created = await prisma.sREIncident.create({ data: body })
  return c.json(created, 201)
})

app.patch('/sre/incidents/:id', async (c) => {
  const id = c.req.param('id')
  const body = await c.req.json()
  const updated = await prisma.sREIncident.update({ where: { id }, data: body })
  return c.json(updated)
})

app.post('/sre/diagnose/:id', async (c) => {
  const id = c.req.param('id')
  const incident = await prisma.sREIncident.findUnique({ where: { id } })
  if (!incident) return c.json({ error: 'Incident not found' }, 404)

  // Simulated AI diagnosis — in production this calls SigNoz MCP + LLM
  const hypotheses = [
    `Service "${incident.service}" is experiencing elevated error rates. Root cause analysis suggests: connection pool exhaustion due to increased traffic spike.`,
    `Based on trace patterns, the latency degradation in "${incident.service}" correlates with database query timeouts. Consider checking connection limits.`,
    `Alert triggered for "${incident.service}": anomaly detection shows 3σ deviation from baseline latency. Hypothesis: downstream dependency degradation causing cascading timeouts.`,
    `Token budget exceeded for agent loop. The runaway pattern indicates an infinite retry cycle — check circuit breaker configuration.`,
  ]
  const hypothesis = hypotheses[Math.floor(Math.random() * hypotheses.length)]

  const updated = await prisma.sREIncident.update({
    where: { id },
    data: {
      hypothesis,
      rootCause: 'Requires deeper investigation. Query SigNoz traces for full span analysis.',
    },
  })
  return c.json(updated)
})

// ── SigNoz Config ───────────────────────────────────────────
app.get('/signoz-config', async (c) => {
  const configs = await prisma.sigNozConfig.findMany({ orderBy: { updatedAt: 'desc' }, take: 1 })
  return c.json({ config: configs[0] ?? null })
})

app.post('/signoz-config', async (c) => {
  const body = await c.req.json()
  const existing = await prisma.sigNozConfig.findFirst()
  if (existing) {
    const updated = await prisma.sigNozConfig.update({ where: { id: existing.id }, data: body })
    return c.json(updated)
  }
  const created = await prisma.sigNozConfig.create({ data: body })
  return c.json(created, 201)
})

app.post('/signoz-config/test', async (c) => {
  const body = await c.req.json()
  const url = body.instanceUrl
  if (!url) return c.json({ error: 'No instance URL configured' }, 400)

  try {
    const res = await fetch(`${url}/api/v1/services`, {
      headers: { 'Authorization': `Bearer ${body.apiKey ?? ''}` },
      signal: AbortSignal.timeout(5000),
    })
    return c.json({ connected: res.ok, status: res.status })
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Connection failed'
    return c.json({ connected: false, error: msg })
  }
})

// ── SigNoz Proxy (metrics, traces, alerts) ──────────────────
app.post('/signoz/query', async (c) => {
  const body = await c.req.json()
  const config = await prisma.sigNozConfig.findFirst()
  if (!config) return c.json({ error: 'SigNoz not configured' }, 400)
  if (!config.connected) return c.json({ error: 'SigNoz not connected' }, 400)

  try {
    const res = await fetch(`${config.instanceUrl}${body.path}`, {
      method: body.method ?? 'GET',
      headers: {
        'Authorization': `Bearer ${config.apiKey}`,
        'Content-Type': 'application/json',
      },
      body: body.body ? JSON.stringify(body.body) : undefined,
      signal: AbortSignal.timeout(10000),
    })
    const data = await res.json()
    return c.json({ data, status: res.status })
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Query failed'
    return c.json({ error: msg }, 502)
  }
})

// ── Seed demo data ──────────────────────────────────────────
app.post('/seed-demo', async (c) => {
  const providers = ['openai', 'anthropic', 'bedrock']
  const models = {
    openai: ['gpt-4o', 'gpt-4o-mini', 'gpt-3.5-turbo'],
    anthropic: ['claude-sonnet-4-5', 'claude-haiku-4-5', 'claude-opus-4'],
    bedrock: ['anthropic.claude-3-5-sonnet', 'anthropic.claude-3-haiku'],
  }
  const agents = ['sre-copilot', 'code-reviewer', 'data-analyst', 'chat-assistant', 'auto-responder']

  const now = Date.now()
  const entries: Array<{
    provider: string; model: string; inputTokens: number; outputTokens: number;
    totalTokens: number; cost: number; latencyMs: number; status: string;
    agentName: string; createdAt: Date;
  }> = []

  for (let i = 0; i < 300; i++) {
    const provider = providers[Math.floor(Math.random() * providers.length)]
    const model = models[provider as keyof typeof models][Math.floor(Math.random() * models[provider as keyof typeof models].length)]
    const inputTokens = Math.floor(Math.random() * 4000) + 100
    const outputTokens = Math.floor(Math.random() * 2000) + 50
    const totalTokens = inputTokens + outputTokens
    const costPerToken = provider === 'openai' ? 0.00001 : provider === 'anthropic' ? 0.000015 : 0.000012
    const cost = Math.round(totalTokens * costPerToken * 10000) / 10000
    const latencyMs = Math.floor(Math.random() * 3000) + 200
    const status = Math.random() > 0.05 ? 'success' : Math.random() > 0.5 ? 'error' : 'rate_limited'
    const agent = agents[Math.floor(Math.random() * agents.length)]
    const hoursAgo = Math.floor(Math.random() * 168) // 7 days
    entries.push({
      provider, model, inputTokens, outputTokens, totalTokens,
      cost, latencyMs, status, agentName: agent,
      createdAt: new Date(now - hoursAgo * 3600 * 1000),
    })
  }

  await prisma.lLMUsage.createMany({ data: entries })

  // Seed budget rules
  const rules = [
    { name: 'Global Daily Budget', scope: 'global', limitType: 'daily', maxTokens: 500000, maxCost: 25, alertThreshold: 0.8, action: 'alert', enabled: true },
    { name: 'Agent Loop Token Cap', scope: 'agent', scopeValue: 'auto-responder', limitType: 'daily', maxTokens: 100000, maxCost: 10, alertThreshold: 0.9, action: 'shutdown', enabled: true },
    { name: 'Monthly Spend Limit', scope: 'global', limitType: 'monthly', maxTokens: 10000000, maxCost: 500, alertThreshold: 0.7, action: 'alert', enabled: true },
  ]
  for (const rule of rules) {
    await prisma.budgetRule.create({ data: rule })
  }

  // Seed SRE incidents
  const incidents = [
    { title: 'High latency on sre-copilot service', description: 'P99 latency spiked to 8.2s (baseline: 1.2s)', severity: 'critical', service: 'sre-copilot', status: 'investigating', hypothesis: 'Connection pool exhaustion due to SigNoz API rate limiting', rootCause: 'Downstream SigNoz MCP server experiencing high load' },
    { title: 'Token budget exceeded for auto-responder', description: 'Agent burned through 150k tokens in 3 minutes', severity: 'warning', service: 'auto-responder', status: 'resolved', hypothesis: 'Runaway retry loop — agent retried failed API calls without exponential backoff', resolution: 'Added circuit breaker with 3-retry limit' },
    { title: 'OpenAI API rate limit triggered', description: '429 errors from OpenAI endpoint', severity: 'warning', service: 'chat-assistant', status: 'open', hypothesis: 'Concurrent agent sessions exceeding tier rate limit' },
    { title: 'Database connection timeout', description: 'Prisma connection pool exhausted under load', severity: 'critical', service: 'api-gateway', status: 'resolved', hypothesis: 'SQLite WAL mode contention with concurrent writes', resolution: 'Switched to connection pooling with PgBouncer pattern' },
  ]
  for (const inc of incidents) {
    await prisma.sREIncident.create({ data: inc })
  }

  // Seed budget alerts
  const alerts = [
    { ruleId: 'seed', ruleName: 'Global Daily Budget', alertType: 'cost_threshold', currentTokens: 420000, currentCost: 21.5, limitTokens: 500000, limitCost: 25, threshold: 0.86, message: 'Global Daily Budget: $21.50 spent (86%)' },
    { ruleId: 'seed', ruleName: 'Agent Loop Token Cap', alertType: 'token_threshold', currentTokens: 95000, currentCost: 8.2, limitTokens: 100000, limitCost: 10, threshold: 0.95, message: 'Agent Loop Token Cap: 95000 tokens used (95%)' },
  ]
  for (const alert of alerts) {
    await prisma.budgetAlert.create({ data: alert })
  }

  return c.json({ ok: true, seeded: { usage: 300, rules: 3, incidents: 4, alerts: 2 } })
})

export default app
